run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports  
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
    - gosimple
    - errcheck

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - revive
        - staticcheck
